languageCode = "en-us"
title = "A simple Hugo site"
baseurl = "/"
theme = "hugo-theme-bootstrap4-blog"
paginate = 5

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[params]
  # Site author
  author = "Your Name"

  # Description/subtitle for homepage (can be Markdown)
  description = "A simple Hugo theme based on the Bootstrap v4 blog example."

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

[params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

[params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = true